const menuData = [
    {
        id: 1,
        title: 'Paneer Tikka Masala',
        category: 'mains',
        cuisine: 'Indian',
        price: 369.00,
        image: getMenuImage('Paneer Tikka Masala', 'mains', 'Indian'),
        desc: 'Smoky paneer cubes simmered in a rich tomato and cashew sauce with aromatic spices.',
        isVeg: true,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 2,
        title: 'Veg Hyderabadi Biryani',
        category: 'mains',
        cuisine: 'Indian',
        price: 429.00,
        image: getMenuImage('Veg Hyderabadi Biryani', 'mains', 'Indian'),
        desc: 'Layered basmati rice with saffron, tender lamb, and warm spices for a fragrant feast.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 3,
        title: 'Mango Lassi',
        category: 'beverages',
        cuisine: 'Indian',
        price: 149.00,
        image: getMenuImage('Mango Lassi', 'beverages', 'Indian'),
        desc: 'Creamy mango yogurt drink finished with a hint of cardamom and honey.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 4,
        title: 'Gulab Jamun Cheesecake',
        category: 'desserts',
        cuisine: 'Indian',
        price: 259.00,
        image: getMenuImage('Gulab Jamun Cheesecake', 'desserts', 'Indian'),
        desc: 'A modern twist on a classic dessert, pairing soft syruped dumplings with rich cheesecake.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 5,
        title: 'Spring Onion Soup',
        category: 'starters',
        cuisine: 'Continental',
        price: 189.00,
        image: getMenuImage('Spring Onion Soup', 'starters', 'Continental'),
        desc: 'Velvety soup with caramelized onions, a splash of sherry, and a crisp herb garnish.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 6,
        title: 'Classic Bruschetta',
        category: 'starters',
        cuisine: 'Italian',
        price: 249.00,
        image: getMenuImage('Classic Bruschetta', 'starters', 'Italian'),
        desc: 'Toasted artisan bread topped with fresh tomatoes, basil, garlic, and balsamic glaze.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 7,
        title: 'Vegetable Spring Rolls',
        category: 'starters',
        cuisine: 'Chinese',
        price: 229.00,
        image: getMenuImage('Vegetable Spring Rolls', 'starters', 'Chinese'),
        desc: 'Golden fried rolls filled with crisp vegetables and served with sweet chili sauce.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 8,
        title: 'Mushroom Risotto',
        category: 'mains',
        cuisine: 'Italian',
        price: 389.00,
        image: getMenuImage('Mushroom Risotto', 'mains', 'Italian'),
        desc: 'Creamy arborio rice cooked with wild mushrooms, parmesan, and white wine.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 9,
        title: 'Tandoori Paneer',
        category: 'mains',
        cuisine: 'Tandoor',
        price: 449.00,
        image: getMenuImage('Tandoori Paneer', 'mains', 'Tandoor'),
        desc: 'Juicy chicken marinated in yogurt and spices, roasted in the tandoor until charred.',
        isVeg: true,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 10,
        title: 'Garlic Butter Mushrooms',
        category: 'mains',
        cuisine: 'Continental',
        price: 529.00,
        image: getMenuImage('Garlic Butter Mushrooms', 'mains', 'Continental'),
        desc: 'Sizzling prawns in garlic butter served with wilted greens and lemon.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 11,
        title: 'Dal Makhani',
        category: 'mains',
        cuisine: 'Indian',
        price: 319.00,
        image: getMenuImage('Dal Makhani', 'mains', 'Indian'),
        desc: 'Slow-cooked black lentils in a creamy tomato gravy with butter and spices.',
        isVeg: true,
        rating: 4.9,
        tags: []
    },
    {
        id: 12,
        title: 'Paneer Korma',
        category: 'mains',
        cuisine: 'Indian',
        price: 379.00,
        image: getMenuImage('Paneer Korma', 'mains', 'Indian'),
        desc: 'Tender chicken in a fragrant cashew and cream sauce with cardamom and cinnamon.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 13,
        title: 'Pav Bhaji',
        category: 'starters',
        cuisine: 'Indian',
        price: 239.00,
        image: getMenuImage('Pav Bhaji', 'starters', 'Indian'),
        desc: 'Butter-toasted buns served with a spiced vegetable mash and tangy onion salad.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 45,
        title: 'Butter Naan',
        category: 'breads',
        cuisine: 'Indian',
        price: 89.00,
        image: getMenuImage('Butter Naan', 'breads', 'Indian'),
        desc: 'Freshly baked naan brushed with melting butter and served warm.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 46,
        title: 'Garlic Naan',
        category: 'breads',
        cuisine: 'Indian',
        price: 99.00,
        image: getMenuImage('Garlic Naan', 'breads', 'Indian'),
        desc: 'Soft naan tossed with garlic butter and fresh herbs for a fragrant finish.',
        isVeg: true,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 47,
        title: 'Tandoori Roti',
        category: 'breads',
        cuisine: 'Indian',
        price: 79.00,
        image: getMenuImage('Tandoori Roti', 'breads', 'Indian'),
        desc: 'Whole wheat roti cooked in the tandoor, with a slightly charred texture.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 48,
        title: 'Laccha Paratha',
        category: 'breads',
        cuisine: 'Indian',
        price: 109.00,
        image: getMenuImage('Laccha Paratha', 'breads', 'Indian'),
        desc: 'Layered flaky paratha served hot with a crisp buttery finish.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 18,
        title: 'Paneer Lababdar',
        category: 'mains',
        cuisine: 'Indian',
        price: 339.00,
        image: getMenuImage('Paneer Lababdar', 'mains', 'Indian'),
        desc: 'Soft paneer cubes in a creamy tomato-onion gravy with fenugreek and spices.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 15,
        title: 'Chole Bhature',
        category: 'mains',
        cuisine: 'Indian',
        price: 299.00,
        image: getMenuImage('Chole Bhature', 'mains', 'Indian'),
        desc: 'Flavorful chickpea curry served with fluffy fried bread and pickle.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 16,
        title: 'Paneer Curry',
        category: 'mains',
        cuisine: 'Indian',
        price: 429.00,
        image: getMenuImage('Paneer Curry', 'mains', 'Indian'),
        desc: 'Coastal-style fish cooked in tangy tamarind and coconut gravy.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 17,
        title: 'Szechuan Noodles',
        category: 'mains',
        cuisine: 'Chinese',
        price: 289.00,
        image: getMenuImage('Szechuan Noodles', 'mains', 'Chinese'),
        desc: 'Stir-fried noodles tossed with vegetables and a bold spicy Szechuan sauce.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 14,
        title: 'Kung Pao Paneer',
        category: 'mains',
        cuisine: 'Chinese',
        price: 359.00,
        image: getMenuImage('Kung Pao Paneer', 'mains', 'Chinese'),
        desc: 'Crispy chicken and peanuts in a sweet-spicy Sichuan glaze.',
        isVeg: true,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 19,
        title: 'Honey Chili Potato',
        category: 'starters',
        cuisine: 'Chinese',
        price: 229.00,
        image: getMenuImage('Honey Chili Potato', 'starters', 'Chinese'),
        desc: 'Crispy potato wedges tossed in honey chili sauce and sesame seeds.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 20,
        title: 'Veg Steamed Dumplings',
        category: 'starters',
        cuisine: 'Chinese',
        price: 249.00,
        image: getMenuImage('Veg Steamed Dumplings', 'starters', 'Chinese'),
        desc: 'Delicate pockets filled with pork and greens, served with soy dipping sauce.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 21,
        title: 'Sweet Corn Soup',
        category: 'starters',
        cuisine: 'Chinese',
        price: 199.00,
        image: getMenuImage('Sweet Corn Soup', 'starters', 'Chinese'),
        desc: 'Silky soup with sweet corn, tofu, and crunchy vegetable confetti.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 22,
        title: 'Chow Mein',
        category: 'mains',
        cuisine: 'Chinese',
        price: 279.00,
        image: getMenuImage('Chow Mein', 'mains', 'Chinese'),
        desc: 'Wok-tossed noodles with crunchy vegetables and savory soy glaze.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 23,
        title: 'Honey Garlic Chicken',
        category: 'mains',
        cuisine: 'Chinese',
        price: 339.00,
        image: getMenuImage('Honey Garlic Chicken', 'mains', 'Chinese'),
        desc: 'Tender chicken in a glossy honey garlic sauce with crunchy greens.',
        isVeg: false,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 24,
        title: 'Veg Tom Yum Soup',
        category: 'starters',
        cuisine: 'Chinese',
        price: 249.00,
        image: getMenuImage('Veg Tom Yum Soup', 'starters', 'Chinese'),
        desc: 'Aromatic broth with shrimp, lemongrass, mushrooms, and chili.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 55,
        title: 'Crispy Chilli Paneer',
        category: 'starters',
        cuisine: 'Chinese',
        price: 269.00,
        image: getMenuImage('Crispy Chilli Paneer', 'starters', 'Chinese'),
        desc: 'Paneer tossed in spicy chili sauce with peppers and sesame seeds.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 56,
        title: 'Sweet and Sour Cauliflower',
        category: 'mains',
        cuisine: 'Chinese',
        price: 329.00,
        image: getMenuImage('Sweet and Sour Cauliflower', 'mains', 'Chinese'),
        desc: 'Crispy pork in a tangy sweet and sour sauce with pineapple and bell peppers.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 57,
        title: 'Veg Dan Dan Noodles',
        category: 'mains',
        cuisine: 'Chinese',
        price: 309.00,
        image: getMenuImage('Veg Dan Dan Noodles', 'mains', 'Chinese'),
        desc: 'Spicy Sichuan noodles with minced pork, peanuts, and chili oil.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 25,
        title: 'Margherita Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 349.00,
        image: getMenuImage('Margherita Pizza', 'pizza', 'Italian'),
        desc: 'Wood-fired pizza with San Marzano tomatoes, fresh mozzarella, and basil.',
        isVeg: true,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 26,
        title: 'Mushroom Bolognese',
        category: 'mains',
        cuisine: 'Italian',
        price: 399.00,
        image: getMenuImage('Mushroom Bolognese', 'mains', 'Italian'),
        desc: 'Classic spaghetti with rich slow-cooked beef ragu and parmesan.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 27,
        title: 'Pesto Gnocchi',
        category: 'mains',
        cuisine: 'Italian',
        price: 419.00,
        image: getMenuImage('Pesto Gnocchi', 'mains', 'Italian'),
        desc: 'Pillowy potato gnocchi tossed with basil pesto and toasted pine nuts.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 28,
        title: 'Caprese Salad',
        category: 'starters',
        cuisine: 'Italian',
        price: 299.00,
        image: getMenuImage('Caprese Salad', 'starters', 'Italian'),
        desc: 'Juicy tomatoes, mozzarella, basil, and balsamic glaze for a light start.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 29,
        title: 'Four Cheese Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 429.00,
        image: getMenuImage('Four Cheese Pizza', 'pizza', 'Italian'),
        desc: 'Creamy blend of mozzarella, gorgonzola, parmesan and ricotta on a crispy crust.',
        isVeg: true,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 30,
        title: 'Tiramisu',
        category: 'desserts',
        cuisine: 'Italian',
        price: 249.00,
        image: getMenuImage('Tiramisu', 'desserts', 'Italian'),
        desc: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream.',
        isVeg: true,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 49,
        title: 'Arancini di Riso',
        category: 'starters',
        cuisine: 'Italian',
        price: 289.00,
        image: getMenuImage('Arancini di Riso', 'starters', 'Italian'),
        desc: 'Golden-fried risotto balls stuffed with cheese and served with marinara dip.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 50,
        title: 'Vegetable Lasagna',
        category: 'mains',
        cuisine: 'Italian',
        price: 449.00,
        image: getMenuImage('Vegetable Lasagna', 'mains', 'Italian'),
        desc: 'Layered pasta baked with rich ragù, béchamel, and melted mozzarella.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 51,
        title: 'Panna Cotta',
        category: 'desserts',
        cuisine: 'Italian',
        price: 219.00,
        image: getMenuImage('Panna Cotta', 'desserts', 'Italian'),
        desc: 'Silky vanilla panna cotta finished with berry compote and roasted almonds.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 31,
        title: 'Ratatouille Tart',
        category: 'starters',
        cuisine: 'Continental',
        price: 299.00,
        image: getMenuImage('Ratatouille Tart', 'starters', 'Continental'),
        desc: 'Buttery pastry topped with roasted vegetables, herbs, and goat cheese.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 32,
        title: 'Mushroom Wellington',
        category: 'mains',
        cuisine: 'Continental',
        price: 699.00,
        image: getMenuImage('Mushroom Wellington', 'mains', 'Continental'),
        desc: 'Succulent beef tenderloin wrapped in mushroom duxelles and puff pastry.',
        isVeg: true,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 33,
        title: 'Caesar Salad',
        category: 'starters',
        cuisine: 'Continental',
        price: 289.00,
        image: getMenuImage('Caesar Salad', 'starters', 'Continental'),
        desc: 'Crisp romaine with parmesan, croutons, and creamy Caesar dressing.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 34,
        title: 'Grilled Portobello Fillet',
        category: 'mains',
        cuisine: 'Continental',
        price: 569.00,
        image: getMenuImage('Grilled Portobello Fillet', 'mains', 'Continental'),
        desc: 'Char-grilled salmon served with lemon thyme butter and roasted potatoes.',
        isVeg: true,
        rating: 4.9,
        tags: ['recommended']
    },
    {
        id: 35,
        title: 'Creamy Mushroom Soup',
        category: 'starters',
        cuisine: 'Continental',
        price: 219.00,
        image: getMenuImage('Creamy Mushroom Soup', 'starters', 'Continental'),
        desc: 'Silky mushroom soup finished with cream and fresh herbs.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 36,
        title: 'Chocolate Fondant',
        category: 'desserts',
        cuisine: 'Continental',
        price: 329.00,
        image: getMenuImage('Chocolate Fondant', 'desserts', 'Continental'),
        desc: 'Decadent molten cake served warm with vanilla bean ice cream.',
        isVeg: true,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 37,
        title: 'Herb Crusted Paneer',
        category: 'mains',
        cuisine: 'Continental',
        price: 449.00,
        image: getMenuImage('Herb Crusted Paneer', 'mains', 'Continental'),
        desc: 'Roasted chicken with a crispy herb crust, side of seasonal vegetables.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 52,
        title: 'Mushroom Confit',
        category: 'mains',
        cuisine: 'Continental',
        price: 689.00,
        image: getMenuImage('Mushroom Confit', 'mains', 'Continental'),
        desc: 'Slow-cooked duck leg served with garlic potatoes and a red wine glaze.',
        isVeg: true,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 53,
        title: 'Veg en Papillote',
        category: 'mains',
        cuisine: 'Continental',
        price: 599.00,
        image: getMenuImage('Veg en Papillote', 'mains', 'Continental'),
        desc: 'Delicate salmon baked in parchment with lemon, herbs, and seasonal vegetables.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 54,
        title: 'Apple Tarte Tatin',
        category: 'desserts',
        cuisine: 'Continental',
        price: 269.00,
        image: getMenuImage('Apple Tarte Tatin', 'desserts', 'Continental'),
        desc: 'Caramelized apple tart served warm with vanilla ice cream.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 38,
        title: 'Tandoori Paneer Tikka',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 279.00,
        image: getMenuImage('Tandoori Paneer Tikka', 'starters', 'Tandoor'),
        desc: 'Paneer cubes marinated in yogurt and spices, charred in the tandoor.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 39,
        title: 'Paneer Kebab Platter',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 339.00,
        image: getMenuImage('Paneer Kebab Platter', 'starters', 'Tandoor'),
        desc: 'Spiced minced meat skewers grilled over charcoal and served with chutney.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 40,
        title: 'Tandoori Mushroom Tikka',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 369.00,
        image: getMenuImage('Tandoori Mushroom Tikka', 'starters', 'Tandoor'),
        desc: 'Tender fish chunks marinated in zingy spices and roasted to perfection.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 41,
        title: 'Naan Basket',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 159.00,
        image: getMenuImage('Naan Basket', 'starters', 'Tandoor'),
        desc: 'Assortment of garlic, butter, and plain naan baked in the tandoor.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 42,
        title: 'Tandoori Mushroom',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 279.00,
        image: getMenuImage('Tandoori Mushroom', 'starters', 'Tandoor'),
        desc: 'Wild mushrooms marinated in spiced yogurt and roasted with charred edges.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 43,
        title: 'Paneer Malai Tikka',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 379.00,
        image: getMenuImage('Paneer Malai Tikka', 'starters', 'Tandoor'),
        desc: 'Creamy chicken skewers seasoned with cardamom, saffron, and cottage cheese.',
        isVeg: true,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 44,
        title: 'Tandoori Mixed Veg Grill',
        category: 'mains',
        cuisine: 'Tandoor',
        price: 599.00,
        image: getMenuImage('Tandoori Mixed Veg Grill', 'mains', 'Tandoor'),
        desc: 'An indulgent platter of tandoori chicken, kebab, fish tikka, and paneer skewers.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 58,
        title: 'Paneer Reshmi Kebab',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 319.00,
        image: getMenuImage('Paneer Reshmi Kebab', 'starters', 'Tandoor'),
        desc: 'Silky chicken kebabs marinated in cream, nuts, and aromatic spices.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 59,
        title: 'Tandoori Mushroom Bites',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 369.00,
        image: getMenuImage('Tandoori Mushroom Bites', 'starters', 'Tandoor'),
        desc: 'Juicy prawns marinated in tandoori spices and char-grilled to smoky perfection.',
        isVeg: true,
        rating: 4.9,
        tags: []
    },
    {
        id: 60,
        title: 'Tandoori Chaap',
        category: 'mains',
        cuisine: 'Tandoor',
        price: 449.00,
        image: getMenuImage('Tandoori Chaap', 'mains', 'Tandoor'),
        desc: 'Spiced soya chaap cooked in the tandoor, served with mint chutney.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 61,
        title: 'Truffle Mushroom Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 479.00,
        image: getMenuImage('Truffle Mushroom Pizza', 'pizza', 'Italian'),
        desc: 'Earthy mushrooms, truffle oil, and fontina cheese on a crisp thin crust.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 62,
        title: 'BBQ Chicken Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 459.00,
        image: getMenuImage('BBQ Chicken Pizza', 'pizza', 'Italian'),
        desc: 'Smoky BBQ chicken, red onions, cilantro, and mozzarella on a hand-stretched pie.',
        isVeg: false,
        rating: 4.7,
        tags: []
    },
    {
        id: 63,
        title: 'Classic Smash Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 349.00,
        image: getMenuImage('Classic Smash Burger', 'burgers', 'Continental'),
        desc: 'Juicy beef patty smashed on the griddle, with cheddar, pickles, and secret sauce.',
        isVeg: false,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 64,
        title: 'Spicy Paneer Burger',
        category: 'burgers',
        cuisine: 'Indian',
        price: 329.00,
        image: getMenuImage('Spicy Paneer Burger', 'burgers', 'Indian'),
        desc: 'Grilled paneer patty with spicy chutney, onions, lettuce, and a soft brioche bun.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 65,
        title: 'Truffle Wagyu Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 599.00,
        image: getMenuImage('Truffle Wagyu Burger', 'burgers', 'Continental'),
        desc: 'Premium wagyu beef with truffle aioli, gruyere cheese, and caramelized onions.',
        isVeg: false,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 66,
        title: 'Affogato',
        category: 'desserts',
        cuisine: 'Italian',
        price: 239.00,
        image: getMenuImage('Affogato', 'desserts', 'Italian'),
        desc: 'Vanilla gelato drowned in hot espresso for a creamy Italian coffee dessert.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 67,
        title: 'Lemon Cheesecake',
        category: 'desserts',
        cuisine: 'Continental',
        price: 269.00,
        image: getMenuImage('Lemon Cheesecake', 'desserts', 'Continental'),
        desc: 'Zesty lemon cheesecake with a buttery graham crust and fresh berry drizzle.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 68,
        title: 'Roomali Roti',
        category: 'breads',
        cuisine: 'Indian',
        price: 89.00,
        image: getMenuImage('Roomali Roti', 'breads', 'Indian'),
        desc: 'Paper-thin handkerchief roti cooked over a hot griddle and folded for softness.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 69,
        title: 'Cheese Kulcha',
        category: 'breads',
        cuisine: 'Indian',
        price: 119.00,
        image: getMenuImage('Cheese Kulcha', 'breads', 'Indian'),
        desc: 'Fluffy kulcha stuffed with melted cheese and baked until golden brown.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 70,
        title: 'Masala Chai',
        category: 'beverages',
        cuisine: 'Indian',
        price: 119.00,
        image: getMenuImage('Masala Chai', 'beverages', 'Indian'),
        desc: 'Fragrant tea brewed with spices, milk, and a touch of sweet honey.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 71,
        title: 'Iced Matcha Latte',
        category: 'beverages',
        cuisine: 'Continental',
        price: 179.00,
        image: getMenuImage('Iced Matcha Latte', 'beverages', 'Continental'),
        desc: 'Smooth matcha latte served over ice with oat milk and a subtle vanilla finish.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 72,
        title: 'Cold Brew Coffee',
        category: 'beverages',
        cuisine: 'Continental',
        price: 159.00,
        image: getMenuImage('Cold Brew Coffee', 'beverages', 'Continental'),
        desc: 'Rich cold brew coffee served chilled over ice with a hint of chocolate and cream.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 73,
        title: 'Roasted Vegetable Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 389.00,
        image: getMenuImage('Roasted Vegetable Pizza', 'pizza', 'Italian'),
        desc: 'Seasonal roasted vegetables, ricotta, and basil on a garlic-infused crust.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 74,
        title: 'Pepperoni Overload Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 459.00,
        image: getMenuImage('Pepperoni Overload Pizza', 'pizza', 'Italian'),
        desc: 'Loaded with pepperoni, mozzarella, and spicy tomato sauce on a chewy crust.',
        isVeg: false,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 75,
        title: 'Blue Cheese Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 389.00,
        image: getMenuImage('Blue Cheese Burger', 'burgers', 'Continental'),
        desc: 'Beef patty topped with blue cheese, caramelized onions, and arugula.',
        isVeg: false,
        rating: 4.8,
        tags: []
    },
    {
        id: 76,
        title: 'Avocado Chickpea Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 329.00,
        image: getMenuImage('Avocado Chickpea Burger', 'burgers', 'Continental'),
        desc: 'Creamy avocado and chickpea patty with lettuce, tomato, and lemon mayo.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 77,
        title: 'Chocolate Lava Cake',
        category: 'desserts',
        cuisine: 'Continental',
        price: 289.00,
        image: getMenuImage('Chocolate Lava Cake', 'desserts', 'Continental'),
        desc: 'Warm molten chocolate cake served with vanilla ice cream.',
        isVeg: true,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 78,
        title: 'Raspberry Mille-Feuille',
        category: 'desserts',
        cuisine: 'Continental',
        price: 289.00,
        image: getMenuImage('Raspberry Mille-Feuille', 'desserts', 'Continental'),
        desc: 'Layers of crisp puff pastry, vanilla cream, and fresh raspberries.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 79,
        title: 'Onion Kulcha',
        category: 'breads',
        cuisine: 'Indian',
        price: 109.00,
        image: getMenuImage('Onion Kulcha', 'breads', 'Indian'),
        desc: 'Soft kulcha stuffed with sweet caramelized onions and baked until golden.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 80,
        title: 'Paneer Paratha',
        category: 'breads',
        cuisine: 'Indian',
        price: 129.00,
        image: getMenuImage('Paneer Paratha', 'breads', 'Indian'),
        desc: 'Flaky wheat paratha stuffed with spiced paneer and grilled to perfection.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 81,
        title: 'Sparkling Elderflower Lemonade',
        category: 'beverages',
        cuisine: 'Continental',
        price: 179.00,
        image: getMenuImage('Sparkling Elderflower Lemonade', 'beverages', 'Continental'),
        desc: 'Light sparkling lemonade infused with elderflower and fresh mint.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 82,
        title: 'Coconut Cold Brew',
        category: 'beverages',
        cuisine: 'Continental',
        price: 189.00,
        image: getMenuImage('Coconut Cold Brew', 'beverages', 'Continental'),
        desc: 'Smooth cold brew coffee blended with creamy coconut milk.',
        isVeg: true,
        rating: 4.7,
        tags: ['special']
    },
    {
        id: 83,
        title: 'Samosa Trio',
        category: 'starters',
        cuisine: 'Indian',
        price: 199.00,
        image: getMenuImage('Samosa Trio', 'starters', 'Indian'),
        desc: 'Crispy golden-fried pastries filled with spiced potato, peas, and herbs. Served with tamarind chutney.',
        isVeg: true,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 84,
        title: 'Onion Bhaji',
        category: 'starters',
        cuisine: 'Indian',
        price: 179.00,
        image: getMenuImage('Onion Bhaji', 'starters', 'Indian'),
        desc: 'Crispy fritters made with thinly sliced onions in a spiced gram flour batter, fried until golden.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 85,
        title: 'Chicken 65',
        category: 'starters',
        cuisine: 'Indian',
        price: 249.00,
        image: getMenuImage('Chicken 65', 'starters', 'Indian'),
        desc: 'Tender chicken pieces marinated in spices and yogurt, deep-fried until crispy and served with curry leaves.',
        isVeg: false,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 86,
        title: 'Paneer Pakora',
        category: 'starters',
        cuisine: 'Indian',
        price: 219.00,
        image: getMenuImage('Paneer Pakora', 'starters', 'Indian'),
        desc: 'Soft paneer cubes coated in spiced gram flour batter and deep-fried until golden. Served with mint chutney.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 87,
        title: 'Seekh Kebab (3 Pieces)',
        category: 'starters',
        cuisine: 'Indian',
        price: 259.00,
        image: getMenuImage('Seekh Kebab (3 Pieces)', 'starters', 'Indian'),
        desc: 'Minced lamb wrapped around skewers with herbs and spices, grilled in the tandoor. Served with lemon and onion.',
        isVeg: false,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 88,
        title: 'Shrimp Koliwada',
        category: 'starters',
        cuisine: 'Indian',
        price: 289.00,
        image: getMenuImage('Shrimp Koliwada', 'starters', 'Indian'),
        desc: 'Succulent shrimp coated in coconut and chili paste, deep-fried until crispy. A coastal Indian delicacy.',
        isVeg: false,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 89,
        title: 'Hara Bhara Kebab',
        category: 'starters',
        cuisine: 'Indian',
        price: 189.00,
        image: getMenuImage('Hara Bhara Kebab', 'starters', 'Indian'),
        desc: 'Green vegetable patties made with spinach, peas, and herbs, pan-fried until crispy. A healthy, flavorful starter.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 90,
        title: 'Fish Pakora',
        category: 'starters',
        cuisine: 'Indian',
        price: 269.00,
        image: getMenuImage('Fish Pakora', 'starters', 'Indian'),
        desc: 'Fresh fish pieces marinated and coated in spiced gram flour batter, deep-fried until crispy and golden.',
        isVeg: false,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 91,
        title: 'Steamed Vegetable Momos',
        category: 'starters',
        cuisine: 'Indian',
        price: 189.00,
        image: getMenuImage('Steamed Vegetable Momos', 'starters', 'Indian'),
        desc: 'Delicate steamed dumplings filled with fresh vegetables, ginger, and garlic. Served with spicy red chili sauce.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 92,
        title: 'Chicken Momos',
        category: 'starters',
        cuisine: 'Indian',
        price: 219.00,
        image: getMenuImage('Chicken Momos', 'starters', 'Indian'),
        desc: 'Tender chicken momos with ginger and scallions, steamed to perfection. Paired with our house chili sauce.',
        isVeg: false,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 93,
        title: 'Paneer & Corn Momos',
        category: 'starters',
        cuisine: 'Indian',
        price: 229.00,
        image: getMenuImage('Paneer & Corn Momos', 'starters', 'Indian'),
        desc: 'Creamy paneer and sweet corn dumplings, steamed until tender. A delightful vegetarian option.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 94,
        title: 'Fried Spicy Chicken Momos',
        category: 'starters',
        cuisine: 'Indian',
        price: 249.00,
        image: getMenuImage('Fried Spicy Chicken Momos', 'starters', 'Indian'),
        desc: 'Crispy fried chicken momos tossed in a fiery chili and garlic sauce. For the adventurous palate.',
        isVeg: false,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 95,
        title: 'Mixed Vegetable Fried Momos',
        category: 'starters',
        cuisine: 'Indian',
        price: 199.00,
        image: getMenuImage('Mixed Vegetable Fried Momos', 'starters', 'Indian'),
        desc: 'Golden-fried dumplings filled with mixed vegetables and spices. Served with sweet and sour sauce.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 96,
        title: 'Jeera Rice',
        category: 'mains',
        cuisine: 'Indian',
        price: 159.00,
        image: getMenuImage('Jeera Rice', 'mains', 'Indian'),
        desc: 'Aromatic basmati rice cooked with cumin seeds and ghee, perfect with curries and gravies.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 97,
        title: 'Vegetable Pulao',
        category: 'mains',
        cuisine: 'Indian',
        price: 219.00,
        image: getMenuImage('Vegetable Pulao', 'mains', 'Indian'),
        desc: 'Fragrant rice simmered with mixed vegetables, whole spices and fresh herbs for a comforting meal.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 98,
        title: 'Vegetable Fried Rice',
        category: 'mains',
        cuisine: 'Chinese',
        price: 249.00,
        image: getMenuImage('Vegetable Fried Rice', 'mains', 'Chinese'),
        desc: 'Wok-tossed rice with shredded chicken, eggs, vegetables and soy-infused flavors.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 99,
        title: 'Crispy Cantonese Tofu',
        category: 'mains',
        cuisine: 'Chinese',
        price: 339.00,
        image: getMenuImage('Crispy Cantonese Tofu', 'mains', 'Chinese'),
        desc: 'Golden battered chicken tossed in a sweet and savory Cantonese glaze.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 100,
        title: 'Shanghai Vegetable Dumplings',
        category: 'starters',
        cuisine: 'Chinese',
        price: 219.00,
        image: getMenuImage('Shanghai Vegetable Dumplings', 'starters', 'Chinese'),
        desc: 'Steamed dumplings filled with mixed vegetables, ginger, and sesame oil.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 101,
        title: 'Ma Po Tofu',
        category: 'mains',
        cuisine: 'Chinese',
        price: 259.00,
        image: getMenuImage('Ma Po Tofu', 'mains', 'Chinese'),
        desc: 'Silken tofu simmered in a spicy Sichuan chili sauce with minced vegetables.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 102,
        title: 'Sesame Chicken',
        category: 'mains',
        cuisine: 'Chinese',
        price: 329.00,
        image: getMenuImage('Sesame Chicken', 'mains', 'Chinese'),
        desc: 'Crispy chicken pieces coated in a toasted sesame and honey glaze.',
        isVeg: false,
        rating: 4.7,
        tags: []
    },
    {
        id: 103,
        title: 'Szechuan Tofu Stir Fry',
        category: 'starters',
        cuisine: 'Chinese',
        price: 239.00,
        image: getMenuImage('Szechuan Tofu Stir Fry', 'starters', 'Chinese'),
        desc: 'Tofu cubes tossed with bell peppers in a bold Szechuan sauce.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 104,
        title: 'Wonton Soup',
        category: 'starters',
        cuisine: 'Chinese',
        price: 189.00,
        image: getMenuImage('Wonton Soup', 'starters', 'Chinese'),
        desc: 'Warm broth with tender wontons filled with pork and shrimp.',
        isVeg: false,
        rating: 4.6,
        tags: []
    },
    {
        id: 105,
        title: 'Singapore Noodles',
        category: 'mains',
        cuisine: 'Chinese',
        price: 269.00,
        image: getMenuImage('Singapore Noodles', 'mains', 'Chinese'),
        desc: 'Thin rice noodles stir-fried with prawns, veggies, and curry-spiced sauce.',
        isVeg: false,
        rating: 4.7,
        tags: []
    },
    {
        id: 106,
        title: 'Ginger Garlic Fish',
        category: 'mains',
        cuisine: 'Chinese',
        price: 339.00,
        image: getMenuImage('Ginger Garlic Fish', 'mains', 'Chinese'),
        desc: 'Pan-seared fish fillet glazed with ginger, garlic, and spring onions.',
        isVeg: false,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 107,
        title: 'Honey Chili Cauliflower',
        category: 'starters',
        cuisine: 'Chinese',
        price: 219.00,
        image: getMenuImage('Honey Chili Cauliflower', 'starters', 'Chinese'),
        desc: 'Crispy cauliflower florets tossed in a sweet and spicy chili sauce.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 108,
        title: 'Chicken Lettuce Wraps',
        category: 'starters',
        cuisine: 'Chinese',
        price: 239.00,
        image: getMenuImage('Chicken Lettuce Wraps', 'starters', 'Chinese'),
        desc: 'Savory minced chicken served in crisp lettuce cups with hoisin sauce.',
        isVeg: false,
        rating: 4.7,
        tags: []
    },
    {
        id: 109,
        title: 'Crispy Plum Pork Ribs',
        category: 'mains',
        cuisine: 'Chinese',
        price: 359.00,
        image: getMenuImage('Crispy Plum Pork Ribs', 'mains', 'Chinese'),
        desc: 'Tender pork ribs glazed in a tangy plum sauce and finished with sesame seeds.',
        isVeg: false,
        rating: 4.8,
        tags: []
    },
    {
        id: 110,
        title: 'Garlic Chilli Baby Corn',
        category: 'starters',
        cuisine: 'Chinese',
        price: 209.00,
        image: getMenuImage('Garlic Chilli Baby Corn', 'starters', 'Chinese'),
        desc: 'Stir-fried baby corn tossed in garlic and chili sauce for a flavorful crunch.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 112,
        title: 'Chicken Parmesan',
        category: 'mains',
        cuisine: 'Italian',
        price: 429.00,
        image: getMenuImage('Chicken Parmesan', 'mains', 'Italian'),
        desc: 'Breaded chicken breast topped with marinara, mozzarella, and parmesan cheese.',
        isVeg: false,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 113,
        title: 'Fettuccine Alfredo',
        category: 'mains',
        cuisine: 'Italian',
        price: 379.00,
        image: getMenuImage('Fettuccine Alfredo', 'mains', 'Italian'),
        desc: 'Creamy fettuccine tossed with parmesan, butter, and cracked black pepper.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 114,
        title: 'Pesto Ravioli',
        category: 'mains',
        cuisine: 'Italian',
        price: 349.00,
        image: getMenuImage('Pesto Ravioli', 'mains', 'Italian'),
        desc: 'Ricotta-filled ravioli smothered in fresh basil pesto and toasted pine nuts.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 115,
        title: 'Sicilian Eggplant Parmigiana',
        category: 'mains',
        cuisine: 'Italian',
        price: 319.00,
        image: getMenuImage('Sicilian Eggplant Parmigiana', 'mains', 'Italian'),
        desc: 'Layers of roasted eggplant, tomato sauce, and parmesan baked until bubbly.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 116,
        title: 'Lemon Risotto',
        category: 'mains',
        cuisine: 'Italian',
        price: 359.00,
        image: getMenuImage('Lemon Risotto', 'mains', 'Italian'),
        desc: 'Creamy arborio rice cooked with lemon zest, white wine, and parmesan.',
        isVeg: true,
        rating: 4.7,
        tags: ['special']
    },
    {
        id: 117,
        title: 'Burrata Caprese',
        category: 'starters',
        cuisine: 'Italian',
        price: 279.00,
        image: getMenuImage('Burrata Caprese', 'starters', 'Italian'),
        desc: 'Creamy burrata served with heirloom tomatoes, basil, balsamic glaze, and olive oil.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 118,
        title: 'Garlic Rosemary Focaccia',
        category: 'starters',
        cuisine: 'Italian',
        price: 199.00,
        image: getMenuImage('Garlic Rosemary Focaccia', 'starters', 'Italian'),
        desc: 'Warm focaccia bread with garlic, rosemary, and sea salt, perfect for sharing.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 119,
        title: 'Meatball Parmigiana',
        category: 'mains',
        cuisine: 'Italian',
        price: 399.00,
        image: getMenuImage('Meatball Parmigiana', 'mains', 'Italian'),
        desc: 'Juicy meatballs simmered in tomato sauce and topped with melted mozzarella.',
        isVeg: false,
        rating: 4.7,
        tags: ['special']
    },
    {
        id: 120,
        title: 'Polenta Fries with Truffle Aioli',
        category: 'starters',
        cuisine: 'Italian',
        price: 249.00,
        image: getMenuImage('Polenta Fries with Truffle Aioli', 'starters', 'Italian'),
        desc: 'Crunchy golden polenta fries served with creamy truffle aioli.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 121,
        title: 'Achari Paneer Tikka',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 289.00,
        image: getMenuImage('Achari Paneer Tikka', 'starters', 'Tandoor'),
        desc: 'Paneer cubes marinated in tangy achari spices and charred in the tandoor.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 122,
        title: 'Tandoori Lamb Chops',
        category: 'mains',
        cuisine: 'Tandoor',
        price: 559.00,
        image: getMenuImage('Tandoori Lamb Chops', 'mains', 'Tandoor'),
        desc: 'Succulent lamb chops marinated in aromatic spices and roasted over charcoal.',
        isVeg: false,
        rating: 4.9,
        tags: ['bestseller']
    },
    {
        id: 123,
        title: 'Tandoori Broccoli',
        category: 'starters',
        cuisine: 'Tandoor',
        price: 229.00,
        image: getMenuImage('Tandoori Broccoli', 'starters', 'Tandoor'),
        desc: 'Broccoli florets marinated with yogurt and spices, grilled until tender.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 124,
        title: 'Tandoori Butter Chicken',
        category: 'mains',
        cuisine: 'Tandoor',
        price: 499.00,
        image: getMenuImage('Tandoori Butter Chicken', 'mains', 'Tandoor'),
        desc: 'Rich butter chicken with smoky tandoori flavor, served with a creamy tomato gravy.',
        isVeg: false,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 125,
        title: 'Cheese Garlic Naan',
        category: 'breads',
        cuisine: 'Indian',
        price: 119.00,
        image: getMenuImage('Cheese Garlic Naan', 'breads', 'Indian'),
        desc: 'Soft naan brushed with garlic butter and topped with melted cheese.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 126,
        title: 'Peshawari Naan',
        category: 'breads',
        cuisine: 'Indian',
        price: 129.00,
        image: getMenuImage('Peshawari Naan', 'breads', 'Indian'),
        desc: 'Sweet and nutty naan stuffed with dried fruits and nuts for a rich accompaniment.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 127,
        title: 'Paneer Kulcha',
        category: 'breads',
        cuisine: 'Indian',
        price: 139.00,
        image: getMenuImage('Paneer Kulcha', 'breads', 'Indian'),
        desc: 'Fluffy kulcha stuffed with spiced paneer and charred to golden perfection.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 128,
        title: 'Ajwain Naan',
        category: 'breads',
        cuisine: 'Indian',
        price: 99.00,
        image: getMenuImage('Ajwain Naan', 'breads', 'Indian'),
        desc: 'Aromatic flatbread flavored with carom seeds and served warm with curries.',
        isVeg: true,
        rating: 4.5,
        tags: []
    },
    {
        id: 129,
        title: 'Multigrain Roti',
        category: 'breads',
        cuisine: 'Indian',
        price: 109.00,
        image: getMenuImage('Multigrain Roti', 'breads', 'Indian'),
        desc: 'Healthy multigrain roti served hot, packed with fiber and subtle spices.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 130,
        title: 'Stuffed Aloo Paratha',
        category: 'breads',
        cuisine: 'Indian',
        price: 119.00,
        image: getMenuImage('Stuffed Aloo Paratha', 'breads', 'Indian'),
        desc: 'Layered paratha filled with spiced mashed potato and served with butter.',
        isVeg: true,
        rating: 4.8,
        tags: ['bestseller']
    },
    {
        id: 131,
        title: 'Jowar Bhakri',
        category: 'breads',
        cuisine: 'Indian',
        price: 109.00,
        image: getMenuImage('Jowar Bhakri', 'breads', 'Indian'),
        desc: 'Rustic jowar flatbread with a hearty texture and earthy flavor.',
        isVeg: true,
        rating: 4.5,
        tags: []
    },
    {
        id: 132,
        title: 'Mediterranean Veg Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 399.00,
        image: getMenuImage('Mediterranean Veg Pizza', 'pizza', 'Italian'),
        desc: 'Crisp pizza topped with olives, artichokes, bell peppers, and feta.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 133,
        title: 'Neapolitan Margherita',
        category: 'pizza',
        cuisine: 'Italian',
        price: 329.00,
        image: getMenuImage('Neapolitan Margherita', 'pizza', 'Italian'),
        desc: 'Classic wood-fired pizza with tomato, mozzarella, basil, and olive oil.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 134,
        title: 'Chicken Tikka Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 429.00,
        image: getMenuImage('Chicken Tikka Pizza', 'pizza', 'Italian'),
        desc: 'Spiced chicken tikka, onions, and peppers on a cheesy pizza base.',
        isVeg: false,
        rating: 4.7,
        tags: ['special']
    },
    {
        id: 135,
        title: 'Veggie Delight Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 379.00,
        image: getMenuImage('Veggie Delight Pizza', 'pizza', 'Italian'),
        desc: 'Loaded with zucchini, mushrooms, bell peppers, olives, and tomatoes.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 136,
        title: 'Spinach Ricotta Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 389.00,
        image: getMenuImage('Spinach Ricotta Pizza', 'pizza', 'Italian'),
        desc: 'Creamy ricotta and spinach with a garlic-infused crust.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 137,
        title: 'Prawn Pesto Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 449.00,
        image: getMenuImage('Prawn Pesto Pizza', 'pizza', 'Italian'),
        desc: 'Prawns, pesto sauce, cherry tomatoes, and mozzarella on a crisp base.',
        isVeg: false,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 138,
        title: 'Mushroom Truffle Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 429.00,
        image: getMenuImage('Mushroom Truffle Pizza', 'pizza', 'Italian'),
        desc: 'Sautéed mushrooms, truffle oil, and fontina cheese on a thin crust.',
        isVeg: true,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 139,
        title: 'Buffalo Chicken Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 439.00,
        image: getMenuImage('Buffalo Chicken Pizza', 'pizza', 'Italian'),
        desc: 'Spicy buffalo chicken, blue cheese, and celery on a crunchy crust.',
        isVeg: false,
        rating: 4.7,
        tags: []
    },
    {
        id: 140,
        title: 'Caramelized Onion Pizza',
        category: 'pizza',
        cuisine: 'Italian',
        price: 379.00,
        image: getMenuImage('Caramelized Onion Pizza', 'pizza', 'Italian'),
        desc: 'Sweet caramelized onions, goat cheese, and arugula on a golden crust.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 141,
        title: 'Spicy Chicken Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 329.00,
        image: getMenuImage('Spicy Chicken Burger', 'burgers', 'Continental'),
        desc: 'Zesty chicken patty with jalapeño slaw, cheese, and chipotle mayo.',
        isVeg: false,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 142,
        title: 'Fish Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 319.00,
        image: getMenuImage('Fish Burger', 'burgers', 'Continental'),
        desc: 'Crispy fish fillet with tartar sauce, lettuce, and pickled onions.',
        isVeg: false,
        rating: 4.6,
        tags: []
    },
    {
        id: 143,
        title: 'Paneer Tikka Burger',
        category: 'burgers',
        cuisine: 'Indian',
        price: 299.00,
        image: getMenuImage('Paneer Tikka Burger', 'burgers', 'Indian'),
        desc: 'Grilled paneer tikka with mint chutney, onions, and spicy mayo.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 144,
        title: 'Mushroom Swiss Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 349.00,
        image: getMenuImage('Mushroom Swiss Burger', 'burgers', 'Continental'),
        desc: 'Sautéed mushrooms, Swiss cheese, and caramelized onions on a soft brioche bun.',
        isVeg: false,
        rating: 4.7,
        tags: []
    },
    {
        id: 145,
        title: 'BBQ Bacon Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 379.00,
        image: getMenuImage('BBQ Bacon Burger', 'burgers', 'Continental'),
        desc: 'Smoky bacon, BBQ sauce, cheddar, and crispy onion rings.',
        isVeg: false,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 146,
        title: 'Grilled Veggie Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 289.00,
        image: getMenuImage('Grilled Veggie Burger', 'burgers', 'Continental'),
        desc: 'House-made veggie patty with avocado, lettuce, tomato, and herb mayo.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 147,
        title: 'Loaded Cheese Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 369.00,
        image: getMenuImage('Loaded Cheese Burger', 'burgers', 'Continental'),
        desc: 'Double cheddar, melted onions, and smoky sauce on a juicy beef patty.',
        isVeg: false,
        rating: 4.7,
        tags: ['bestseller']
    },
    {
        id: 148,
        title: 'Falafel Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 299.00,
        image: getMenuImage('Falafel Burger', 'burgers', 'Continental'),
        desc: 'Crispy falafel patty with tahini sauce, pickled veggies, and greens.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 149,
        title: 'Chicken Kebab Burger',
        category: 'burgers',
        cuisine: 'Indian',
        price: 339.00,
        image: getMenuImage('Chicken Kebab Burger', 'burgers', 'Indian'),
        desc: 'Spiced chicken kebab layered with onions, chutney, and fresh greens.',
        isVeg: false,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 150,
        title: 'Lamb Burger',
        category: 'burgers',
        cuisine: 'Continental',
        price: 389.00,
        image: getMenuImage('Lamb Burger', 'burgers', 'Continental'),
        desc: 'Juicy lamb patty with mint yogurt, cucumber, and roasted pepper relish.',
        isVeg: false,
        rating: 4.7,
        tags: ['special']
    },
    {
        id: 151,
        title: 'Rasmalai',
        category: 'desserts',
        cuisine: 'Indian',
        price: 229.00,
        image: getMenuImage('Rasmalai', 'desserts', 'Indian'),
        desc: 'Soft paneer dumplings soaked in saffron milk and pistachio flakes.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 152,
        title: 'Gajar Halwa',
        category: 'desserts',
        cuisine: 'Indian',
        price: 199.00,
        image: getMenuImage('Gajar Halwa', 'desserts', 'Indian'),
        desc: 'Warm carrot pudding tempered with ghee, nuts, and aromatic spices.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 153,
        title: 'Chocolate Brownie Sundae',
        category: 'desserts',
        cuisine: 'Continental',
        price: 249.00,
        image: getMenuImage('Chocolate Brownie Sundae', 'desserts', 'Continental'),
        desc: 'Warm brownie served with vanilla ice cream, chocolate sauce, and nuts.',
        isVeg: true,
        rating: 4.9,
        tags: ['special']
    },
    {
        id: 154,
        title: 'Kesar Kulfi',
        category: 'desserts',
        cuisine: 'Indian',
        price: 179.00,
        image: getMenuImage('Kesar Kulfi', 'desserts', 'Indian'),
        desc: 'Creamy saffron ice cream garnished with pistachios and almond slices.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 155,
        title: 'Mango Cheesecake',
        category: 'desserts',
        cuisine: 'Continental',
        price: 259.00,
        image: getMenuImage('Mango Cheesecake', 'desserts', 'Continental'),
        desc: 'Rich cheesecake layered with mango puree and tropical flavor.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 156,
        title: 'Caramel Flan',
        category: 'desserts',
        cuisine: 'Continental',
        price: 229.00,
        image: getMenuImage('Caramel Flan', 'desserts', 'Continental'),
        desc: 'Silky caramel custard topped with caramel sauce and fresh berries.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 157,
        title: 'Masala Chai',
        category: 'beverages',
        cuisine: 'Indian',
        price: 119.00,
        image: getMenuImage('Masala Chai', 'beverages', 'Indian'),
        desc: 'Warm spiced tea brewed with cardamom, cinnamon, ginger, and milk.',
        isVeg: true,
        rating: 4.8,
        tags: []
    },
    {
        id: 158,
        title: 'Rose Lassi',
        category: 'beverages',
        cuisine: 'Indian',
        price: 139.00,
        image: getMenuImage('Rose Lassi', 'beverages', 'Indian'),
        desc: 'Creamy yogurt drink infused with rose syrup and a hint of cardamom.',
        isVeg: true,
        rating: 4.7,
        tags: ['recommended']
    },
    {
        id: 159,
        title: 'Sparkling Mango Cooler',
        category: 'beverages',
        cuisine: 'Continental',
        price: 159.00,
        image: getMenuImage('Sparkling Mango Cooler', 'beverages', 'Continental'),
        desc: 'Refreshingly fizzy mango drink with mint and lime.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 160,
        title: 'Ginger Lemon Honey',
        category: 'beverages',
        cuisine: 'Continental',
        price: 139.00,
        image: getMenuImage('Ginger Lemon Honey', 'beverages', 'Continental'),
        desc: 'Soothing ginger tea with lemon and honey, served warm.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 161,
        title: 'Cold Brew Coffee',
        category: 'beverages',
        cuisine: 'Continental',
        price: 169.00,
        image: getMenuImage('Cold Brew Coffee', 'beverages', 'Continental'),
        desc: 'Smooth cold brew coffee served over ice with a hint of caramel.',
        isVeg: true,
        rating: 4.8,
        tags: ['special']
    },
    {
        id: 162,
        title: 'Hibiscus Iced Tea',
        category: 'beverages',
        cuisine: 'Continental',
        price: 149.00,
        image: getMenuImage('Hibiscus Iced Tea', 'beverages', 'Continental'),
        desc: 'Chilled hibiscus tea with citrus and a touch of sweetness.',
        isVeg: true,
        rating: 4.6,
        tags: []
    },
    {
        id: 163,
        title: 'Orange Mojito',
        category: 'beverages',
        cuisine: 'Continental',
        price: 159.00,
        image: getMenuImage('Orange Mojito', 'beverages', 'Continental'),
        desc: 'Zesty orange drink with mint, soda, and a splash of lime.',
        isVeg: true,
        rating: 4.7,
        tags: []
    },
    {
        id: 164,
        title: 'Vanilla Cold Brew',
        category: 'beverages',
        cuisine: 'Continental',
        price: 169.00,
        image: getMenuImage('Vanilla Cold Brew', 'beverages', 'Continental'),
        desc: 'Cold brew coffee blended with vanilla syrup and almond milk.',
        isVeg: true,
        rating: 4.8,
        tags: ['recommended']
    },
    {
        id: 165,
        title: 'Coconut Water Cooler',
        category: 'beverages',
        cuisine: 'Continental',
        price: 149.00,
        image: getMenuImage('Coconut Water Cooler', 'beverages', 'Continental'),
        desc: 'Fresh coconut water mixed with mint and lime for a tropical refreshment.',
        isVeg: true,
        rating: 4.6,
        tags: []
    }
];
